# AsheshDevelopment
# _config.yml

title: "AsheshDev"
email: "asheshplays.matrix777@passinbox.com"
description: >-
  Welcome to Ashesh's Development site. This is the official documentation and portfolio.
baseurl: "/asheshdev" # The repository name on GitHub.
url: "https://asheshplays.github.io" # Your GitHub Pages URL.

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed

# Excluded files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
